language: php
php:
  - 7.4
before_script:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.sectheater vcs https://github.com/sectheater/laravel-datatable.git
  - composer require sectheater/laravel-datatables:dev-master
  - composer update
  - php artisan key:generate
  - composer dump-autoload -o
  - cd ./vendor/sectheater/laravel-datatables
script:
  - vendor/bin/phpunit
