language: php
php:
  - 7.4
before_script:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.sectheater vcs https://github.com/sectheater/laravel-datatable.git
  - composer require sectheater/laravel-datatables:dev-master
  - php artisan key:generate
  - echo '<?php ' > routes/api.php
  - php artisan clear-compiled
  - php artisan optimize
  - composer dump-autoload
  - cd ./vendor/sectheater/laravel-datatables
  - composer install
  - composer dump-autoload -o
script: "phpunit"
